name: sovarpc
description: "NosoSova + RPC"
publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.4.10
  flutter_gen: ^5.3.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  provider: ^6.1.2
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.2
  path: ^1.8.3
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  http: ^1.2.0
  window_manager: ^0.3.8
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  file_picker: ^5.5.0
  nososova:
    path: ../
  noso_dart: 1.2.4
  noso_rest_api:
    git: https://github.com/Noso-Project/noso_rest_api.git
  args: ^2.5.0
  settings_yaml: ^8.0.1
  logging: ^1.2.0
  logging_appenders: ^1.3.0
  ansicolor: ^2.0.2


dev_dependencies:
  flutter_lints: ^3.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

platforms:
  linux:
  macos:
  windows: