name: NosoSova Main Manual Build

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  FLUTTER_VERSION: 3.22.3
  APP_FOLDER_NAME: NosoSova

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows (windows-latest)
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Rename folder to ${{ env.APP_FOLDER_NAME }}
        shell: pwsh
        run: |
          Rename-Item -Path build/windows/x64/runner/Release -NewName ${{ env.APP_FOLDER_NAME }}

      - name: Move DLL files to ${{ env.APP_FOLDER_NAME }}
        shell: pwsh
        run: |
          Move-Item -Path dlls/msvcp140.dll -Destination build/windows/x64/runner/${{ env.APP_FOLDER_NAME }}/
          Move-Item -Path dlls/msvcp140_1.dll -Destination build/windows/x64/runner/${{ env.APP_FOLDER_NAME }}/
          Move-Item -Path dlls/vcruntime140.dll -Destination build/windows/x64/runner/${{ env.APP_FOLDER_NAME }}/
          Move-Item -Path dlls/vcruntime140_1.dll -Destination build/windows/x64/runner/${{ env.APP_FOLDER_NAME }}/

      - name: Archive Windows build
        run: |
          tar -czf NosoSova-windows-latest-x86_64.tar.gz -C build/windows/x64/runner ${{ env.APP_FOLDER_NAME }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: NosoSova-windows-latest-x86_64
          path: NosoSova-windows-latest-x86_64.tar.gz

  build-linux:
    name: Build Linux (ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt install -y ninja-build libgtk-3-dev

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: |
          pip install pyyaml

      - name: Extract Release Info
        id: extract_release_info
        run: python extract_release_info.py

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: |
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: Rename folder to ${{ env.APP_FOLDER_NAME }}
        run: |
          mv build/linux/x64/release/bundle build/linux/x64/release/${{ env.APP_FOLDER_NAME }}

      - name: Archive Linux build
        run: |
          tar -czf NosoSova-ubuntu-latest-x86_64.tar.gz -C build/linux/x64/release ${{ env.APP_FOLDER_NAME }}

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: NosoSova-ubuntu-latest-x86_64
          path: NosoSova-ubuntu-latest-x86_64.tar.gz

      - name: Upload changelog.txt
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog.txt

  build-android:
    name: Build Android (ubuntu-latest;flutter 3.22.3;Java zulu 17)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: 🔧 Build APK
        env:
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS_ANDROID }}
        run: flutter build apk --release

      - name: Move APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk NosoSova-android.apk

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: NosoSova-android
          path: NosoSova-android.apk

  build-macos:
    name: Build macOS (macos-latest;flutter 3.22.3)
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Enable Macos
        run: flutter config --enable-macos-desktop

      - name: Build macOS app
        run: flutter build macos --release

      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          echo "Create Keychain"
          security create-keychain -p $MACOS_CERTIFICATE_PWD build.keychain
          echo "Assign to Login Keychain"
          security default-keychain -s build.keychain
          echo "Unlock the Login Keychain"
          security unlock-keychain -p $MACOS_CERTIFICATE_PWD build.keychain
          echo "Import certificate"
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          echo "Set Key Partition"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_CERTIFICATE_PWD build.keychain
          echo "Find Identity"
          security find-identity
          echo "Sign the app"
          /usr/bin/codesign --force --deep -s 6FB8K959N9 build/macos/Build/Products/Release/NosoSova.app

      - name: Create a dmg
        run: |
          brew install create-dmg
          create-dmg \
          --volname "NosoSova" \
          --window-pos 200 120 \
          --window-size 800 529 \
          --icon-size 130 \
          --text-size 14 \
          --icon "NosoSova.app" 260 250 \
          --hide-extension "NosoSova.app" \
          --app-drop-link 540 250 \
          --hdiutil-quiet \
          "build/macos/Build/Products/Release/NosoSova-macos-latest-x86_64.dmg" \
          "build/macos/Build/Products/Release/NosoSova.app"

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: NosoSova-macos-latest-x86_64
          path: build/macos/Build/Products/Release/NosoSova-macos-latest-x86_64.dmg

